language: node_js

node_js:
  - '10'

cache: yarn

notifications:
  email: false

install:
  - travis_retry yarn

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test
      script: yarn test
    - stage: release
      script: yarn semantic-release

stages:
  - lint
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
